application/config/autoload.php, application/config/config.php, application/config/database.php
=> first framework config

application/config/autoload.php, application/controllers/Auth.php, application/controllers/User.php, application/helpers/meeting_helper.php
=> added meeting helper

README.md, application/config/config.php, application/controllers/Auth.php, application/controllers/User.php, application/models/BaseModel.php, application/models/PUAModel.php, application/views/layout/app/app_sidebar.php, application/views/layout/app/app_topbar.php, assets/js/calendar.js
modified some codes by added Models and cleaned up useless coding code on controller and add more views features
=> modified some codes by added Models and cleaned up useless coding on controller and add more viewes features

application/controllers/Admin.php, database/e-meeting.sql
app_admin_module consist of all feature in the application on admin role
=> create new module called app_admin_module

application/controllers/Admin.php, application/views/modul/user/index.php
=> make user dashboard view part 1

application/controllers/Admin.php, application/helpers/meeting_helper.php, application/models/DashboardModel.php, application/views/layout/app/app_footer.php, application/views/modul/admin/index.php
update dashboard views by added table that shows todays meeting and counts meeting by status
=> make admin dashboard view part 2 - create dashboard

application/controllers/Admin.php, application/controllers/Auth.php, application/models/DashboardModel.php, application/views/auth/blocked.php, application/views/modul/admin/index.php, assets/css/custom.css
make admin dashboard view part 4 - added search view & blocked page
=> make admin dashboard view part 4 - added search view & blocked page

application/views/auth/login.php, application/views/layout/app/app_footer.php, application/views/layout/app/app_sidebar.php, application/views/layout/app/app_topbar.php, application/views/modul/admin/index.php, assets/css/custom.css
make admin dashboard view part 5 - modified result search view using bootstrap 4 list view
=> make admin dashboard view part 5 - modified result search view using bootstrap 4 list view

application/config/config.php, application/controllers/Admin.php, application/models/DashboardModel.php, application/views/auth/blocked.php, application/views/errors/html/error_404.php, application/views/errors/html/error_db.php, application/views/errors/html/error_general.php, application/views/modul/admin/index.php, assets/css/custom.css
make admin dashboard view part 6 - created search module by date and modified error pages
=> make admin dashboard view part 6 - created search module by date and modified error pages

application/controllers/Admin.php, application/controllers/Menu.php, application/models/MenuModel.php, application/views/layout/app/app_footer.php, application/views/modul/menu/index.php, assets/css/custom.css
=> create crud module app_menu

application/controllers/Admin.php, application/models/Account_model.php
App Auth part 1 - refactoring old auth code
@davedjoh
=> App Auth part 1 - refactoring old auth code

application/views/admin/index.php
make admin dashboard view part 15 - start to modified dashboard
=> make admin dashboard view part 15 - start to modified dashboard

application/controllers/Meeting.php, application/views/layout/footer.php, application/views/layout/header.php, application/views/meeting/index.php, assets/css/custom.css, database/e-meeting.sql
make admin dashboard view part 28 - add tags input & databases refactoring
=> make admin dashboard view part 28 - add tags input & databases refactoring

application/controllers/Calendar.php, application/models/Calendar_model.php, application/views/frontend/about.php, application/views/frontend/calendar.php, application/views/frontend/home.php
Frontend Part 4 - modified home, about & calendar components by added style & js
=> Frontend Part 4 - modified home, about & calendar components by added style & js

application/controllers/Auth.php, application/views/frontend/calendar.php, application/views/history/index.php
Frontend Part 5 - design nav bar layout, hero component & functionality
@ivandi1980
=> Frontend Part 5 - design nav bar layout, hero component & functionality

application/controllers/Type.php, application/models/Type_model.php, application/views/type/index.php, application/views/type/subtype.php
backend Part 4 - adding subMedia Type extends to MediaType
=> backend Part 4 - adding subMedia Type extends to MediaType

application/controllers/Admin.php, application/models/Department_model.php, application/views/admin/account.php, application/views/frontend/home.php, application/views/meeting/index.php, application/views/meeting/userindex.php
backend Part 9 - modified calendar backend
=> backend Part 9 - modified calendar backend

application/views/meeting/index.php, database/rapat.sql
=> Fullstack Part 3 - Calendar & Meeting Updated Code

application/views/frontend/getcalendar.php, assets/css/customs-style.css, assets/js/customsjs/customs-calendar.js
=> New FullStack 5 - Refactoring Calendar Code Part 1

application/controllers/Calendar.php, application/controllers/Meeting.php, application/helpers/meeting_helper.php, application/views/layout/footer.php, application/views/meeting/index.php, application/views/meeting/userindex.php, assets/js/customsjs/customs-calendar.js
Update input form create meeting by added feature :
- enable/disable checkbox when user choose online/offline meeting
- enable/disable textbox when user ticked on the checkbox
=> Master Rapat - Updated Legacy Four

application/helpers/dropdown_helper.php, application/views/frontend/getcalendar.php
Legacy_Update - Refactor Media Dropdown (UPDATED)
@davedjoh
=> Legacy_Update - Refactor Media Dropdown (UPDATED)

application/helpers/meeting_helper.php, assets/css/custom.css
Legacy_Update - Added Feature ZoomID Search part 2 (UPDATED)
=> Legacy_Update - Added Feature ZoomID Search part 2 (UPDATED)

application/controllers/Zoom.php, application/helpers/meeting_helper.php, application/models/Zoom_model.php, application/views/auth/login.php, application/views/layout/front_topbar.php, application/views/user/index.php, application/views/zoom/index.php, assets/css/custom.css, database/rapat.sql
Legacy_Update - Added ZoomID Module (UPDATED)
=> Legacy_Update - Added ZoomID Module (UPDATED)

application/controllers/Admin.php, application/views/admin/account.php, application/views/department/index.php, application/views/department/subdepartment.php, application/views/layout/footer.php, application/views/meeting/userindex.php, application/views/menu/index.php, application/views/menu/submenu.php, application/views/role/index.php, application/views/type/index.php, application/views/type/subtype.php, application/views/zoom/index.php, database/rapat.sql
Legacy_Update - Refactor erapat Codes (UPDATED)
=> Legacy_Update - Refactor erapat Codes (UPDATED)

application/controllers/Meeting.php, application/controllers/Zoom.php, application/helpers/meeting_helper.php, application/models/Meeting_model.php, application/models/Zoom_model.php, application/views/layout/footer.php, application/views/zoom/index.php, assets/css/custom.css, database/rapat.sql
Legacy_Update - Added Feature check status Meeting (UPDATED)
=> Legacy_Update - Added Feature check status Meeting (UPDATED)

application/controllers/Feed.php, application/controllers/Meeting.php, application/helpers/meeting_helper.php, application/models/Meeting_model.php, application/models/Type_model.php, application/models/Zoom_model.php, application/views/feed/pembaharuan.php, application/views/feed/penjelajahan.php, application/views/layout/footer.php, application/views/meeting/index.php, assets/css/custom.css, database/rapat.sql
Legacy_Update - Refactor Feature Feed (UPDATED)
=> Legacy_Update - Refactor Feature Feed (UPDATED)

application/controllers/Feed.php, application/controllers/History.php, application/models/History_model.php, application/models/Meeting_model.php, application/views/feed/pembaharuan.php, application/views/feed/penjelajahan.php, application/views/history/searchdept.php, application/views/zoom/index.php
Legacy_Update - Refactor Feature check Zoom Id (UPDATED)
=> Legacy_Update - Refactor Feature check Zoom Id (UPDATED)

application/controllers/Auth.php, application/controllers/History.php, application/views/auth/login.php, application/views/history/userindex.php, application/views/layout/front_topbar.php, application/views/layout/sidebar.php, database/rapat.sql
"Legacy_Update - Refactor Auth-Login (UPDATED)"
@useername 
@ivandi1980 
@davedjoh
=> "Legacy_Update - Refactor Auth-Login (UPDATED)"

application/controllers/Form.php, application/views/feed/pembaharuan.php, application/views/forms/index.php, application/views/frontend/calendar.php
Legacy_Update - Added feature Create Forms (LATEST)
=> Legacy_Update - Added feature Create Forms (LATEST)

application/views/layout/footer.php
Legacy_Update - Added Tynimce Plugin
=> Legacy_Update - Added Tynimce Plugin

application/controllers/Meeting.php, application/helpers/meeting_helper.php, application/models/Meeting_model.php, application/views/meeting/index.php, application/views/meeting/userindex.php, application/views/zoom/index.php, db/rapat.sql
Legacy_Update - Added Zoom Triggered (UPDATED)
=> Legacy_Update - Added Zoom Triggered (UPDATED)

application/controllers/Feed.php, application/controllers/Meeting.php, application/helpers/meeting_helper.php, application/helpers/tanggal_helper.php, application/models/Meeting_model.php, application/views/feed/cekavailzoom.php, db/rapat.sql
Legacy_Update - Bug Fixed check zoom (UPDATED)
=> Legacy_Update - Bug Fixed check zoom (UPDATED)

application/controllers/Meeting.php, application/helpers/alert_helper.php, application/helpers/meeting_helper.php, application/models/Meeting_model.php, application/views/meeting/undangan_step_1.php, application/views/meeting/undangan_step_2.php, assets/css/customs-popup.css
Legacy_Update - Modified Upload Undangan
=> Legacy_Update - Modified Upload Undangan

application/models/Zoom_model.php, application/views/layout/sidebar.php, db/rapat.sql
Legacy_Update - disable preview data when user offline
=> Legacy_Update - disable preview data when user offline

application/views/meeting/uploadpages.php
Legacy_Update - Create Page for multi-upload
=> Legacy_Update - Create Page for multi-upload

application/helpers/uploadpages_helper.php, application/views/meeting/userindex.php
Legacy_Update - Create Page for multi-upload (UPDATED)
=> Legacy_Update - Create Page for multi-upload (UPDATED)

.htaccess, application/views/frontend/calendar.php, application/views/frontend/dokumentasi.php, application/views/layout/footer.php, application/views/layout/front_topbar.php, application/views/layout/sidebar.php, assets/css/custom.css
xframeoptions merge
@ivandi1980 
@davedjoh
=> Legacy update - added xframeoptions
